// This function generates a stream of digits representing the quotient
// of num and den in the base specified by radix.
// expand(1, 7, 10)
// == 1, 4, 2, 8, 5, 7, 1, ...
// expand(3, 8, 10)
// == 3, 7, 5, 0, 0, ...
